### ISSUE TITLE
Duplicate shares

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool#50]
```
QueryFailedError: SQLITE_ERROR: no such column: NaN
    at handler (/home/leo/public-pool/src/driver/sqlite/SqliteQueryRunner.ts:113:26)
    at Statement.errBack (/home/leo/public-pool/node_modules/sqlite3/lib/sqlite3.js:15:21) {
  query: 'UPDATE "client_entity" SET "hashRate" = NaN, "deletedAt" = ?, "updatedAt" = ? WHERE ("address" = ? AND "clientName" = ? AND "sessionId" = ?)',
  parameters: [
    undefined,
    '0NaN-aN-aN aN:aN:aN.NaN',
    'tb1**********************',
    'worker',
    'a25199b4'
  ],
  driverError: [Error: SQLITE_ERROR: no such column: NaN] {
    errno: 1,
    code: 'SQLITE_ERROR'
  },
  errno: 1,
  code: 'SQLITE_ERROR'
}
{"id":48,"result":null,"error":[22,"Duplicate share",""]}
```

getting duplicate share on testnet4 with a bitaxe ultra

**Comment by benjamin-wilson** [comment]
I'm not exactly sure how this code path was achieved but the underlying issue has been fixed by initializing hashrate to 0.
https://github.com/benjamin-wilson/public-pool/commit/de2b41a3c1a98a328ef056bdfd1f7d7c6abb57c0

**Comment by Retropex** [comment]
Still getting it:
<img width="244" alt="image" src="https://github.com/user-attachments/assets/17ef6b2b-ef18-4f22-9d66-9a4754c03486">

**Comment by benjamin-wilson** [comment]
Does this only happen on testnet4?

**Comment by Retropex** [comment]
yes, it seems to work normally on mainnet:

<img width="246" alt="image" src="https://github.com/user-attachments/assets/8fd0a51c-eb3f-4f6e-ac1d-be87878e0735">
<img width="261" alt="image" src="https://github.com/user-attachments/assets/e5f10be4-36a4-4c1c-8af8-1d1731480df3">
