### ISSUE TITLE
No longer working with Bitcoin Core v28

### ISSUE THREAD

**Issue by sjkjs** [benjamin-wilson/public-pool#80]
I recently updated my node to Bitcoin Core v28.1. This broke compatibility with Public-Pool which gave me this error message any time a miner connected:

`Error getmininginfo jsonrpc field must be a string`

The miners never seemed to register as connected and didn't show up in the online devices list.

After rolling back the node to v27.2 again the problem went away and everything worked again.

**Comment by remcoros** [comment]
This is has been fixed and merged into master in October last year (https://github.com/benjamin-wilson/public-pool/commit/f9e49a895589ab5d2a839ec5c9ee9053bf0d7220), make sure you run an updated version of Public-Pool.

**Comment by sjkjs** [comment]
I'm running the latest master which includes that commit but I'm still having the problem. I've just noticed another error though which I suspect is probably related:

```
public-pool  | Using ZMQ
public-pool  | ZMQ Connected
public-pool  | Could not reach RPC host
public-pool  | Error getmininginfo jsonrpc field must be a string
public-pool  | API listening on http://0.0.0.0:3334
public-pool  | Stratum server is listening on port 3333
```

It says "Could not reach RPC host" but only when the node is running v28, not when it's v27. Otherwise all configuration is identical between the two.

Relevant parts of bitcoin.conf:

```
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=8332
rpcauth=mempool:<pass hash>
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
```

Relevant parts of .env:

```
BITCOIN_RPC_URL=http://172.18.0.1
BITCOIN_RPC_PORT=8332
BITCOIN_RPC_TIMEOUT=10000
BITCOIN_RPC_USER=mempool
BITCOIN_RPC_PASSWORD=<pass>
BITCOIN_ZMQ_HOST="tcp://172.18.0.1:28332"
```

Note that ZMQ can connect but RPC can't despite both having the same IP address.

I can query the RPC interface using curl:

```
[root@btc public-pool]# curl --user mempool --data-binary '{"jsonrpc": "2.0", "id": "0", "method": "getblockcount", "params": []}' -H
 'content-type: application/json' 172.18.0.1:8332/
Enter host password for user 'mempool':
{"jsonrpc":"2.0","result":880057,"id":"0"}
```

I'm probably missing something obvious here... But I'm not sure what would have changed between v27 and v28 to cause this.

**Comment by sjkjs** [comment]
You're right, I just needed to rebuild the container. I must have missed doing that somehow. All good now, thanks for the help.
